version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: kp_leaves
    environment:
      POSTGRES_USER: kpdev
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kp_leaves_db
    ports:
      - "1432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kp-network

volumes:
  postgres_data:

networks:
  kp-network:
